language: node_js
node_js:
- 6
before_install:
- npm i -g npm@3.10.10
install:
- npm install jui
- npm install jui-core
- npm install jui-grid
- npm install jui-chart
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
deploy:
  provider: heroku
  api_key:
    secure: meR4a1qbSZU2SX0mEVIxmTXTxJfrF12PuLbdCfa4zsNISuow5/bMGglTpCHuOZH1R3ql/o6lzDHoY+7Vr/SJR124Gs7NeDO/ABbIIKgipOnItJRsc8A0O/hQzMVSzlZKteuY7kZL8u1rSnDzbK49ViAbvi9FwSzkjHiJF0aVVpBbvv/Xwxs+8f21I0u6Ndh0ZUpDJ05t9bZOQFa8Z6hSAGVYJs9G5lh8gxhAJXGBe6q6SiSyP1NdYEHMAtS7pjFL/F/t7nGd/xjm1s6KfGdYJsaZmCqpuene/UE0S9nPO/dBdIp+fXVJkfPjQW+9sCUJrHWilqPlcdfkbtAIg4Rv4Tztq0QLRBGFc6Crz9j+Tg9IJWOXLuoPh3X5x2QTd2pCXG0QiNQrxZg/MIAJEGtX1jkA/fs/uM52tNws1u7lUD//Eyh4fzqaNKx6/3RkjP2L0RfFEEppNOjaw7wBkrbfZuUoYIHoKdY019zKDJllczOBvI2OGN47dLTB67SxaQcEi1MxcySyTOYU37LKYdW2lB+fEGPCV+qMDvWRl3dUfT8j21XFIwFFAFPFwa8epdV3jov9nKBQ3TNgMs0t/rfcoR70nxRenxZZDY1szNa9AzdcsC5taVmuCed4501ym/veWQuBIRNMvjwNGh7kiGEu6z+jMgqA2fswQ16OndK7NMg=
  run: npm start
