language: node_js
node_js:
- 6
before_install:
- npm i -g npm@3.10.10
install:
- npm install jui
- npm install jui-core
- npm install jui-grid
- npm install jui-chart
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
deploy:
  api_key:
    secure: tOlL1Yf+4ymozNLFtXOl/ksjPBVuO0f2x6lNt26yTNDa8nADg3Up9qRNl6lQC8D57TJiwQL9P8l8D2IJXrX2ixo5vFoCC7uLOPheEuzZ6OV95lU/g5tVDQjox81W4mYpf0FQMo5OD8rL5xA6u8/6sujhznUFXl/Kba70c6QrbJ5ItKgjZ9WSfW2zXxk0dKqvWKhM7Umbe95epw4CfLk64/Z3jElQMy6/C9NjeeYrhHSrh+NECmzdD6lPuVnQsyDx55Yq8a0ohNl7UMnRAugLckw/pqBhDuP+AD50gr6vEjCS3uhB1sY7Th04JOwoOOe+pziWZbSlSAfVLEzuy12QT4xwjslv2PLokNM0Z1eis681u4V6eSxBYQ5KA7srcZ6IjiwDYGtiSHp4bNQBspQQWahPCpH5ze747sZAO7S1Ba+z98HMzkcwh7IG6EKJrkmz81qcQp4mQlSU4iCSPugOY1hK+05rGIpyc3gAt4agx4Oqwmtoy9HJ6e+9u45YDIzv9cyPDD5s5wR2GTGhFs/0dDgzkyRGGDgyXdrbZJLBhHddlERwNIp55Z0bqBMLAxO8zY72f6CRbBGowH12zFLJmX8jpZZGEE1agLOgsbJKAzWQ+CFEXHizqdrG/OwWHlF05THDNYi8xxDiu/nxImdczK9B8w5+1NUeoy5oS3+ow7M=
