language: node_js
node_js:
- 6
before_install:
- npm i -g npm@3.10.10
install:
- npm install jui
- npm install jui-core
- npm install jui-grid
- npm install jui-chart
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
deploy:
  provider: heroku
  api_key:
    secure: rPXZy3sJVhlMSLNdRvt/6+HawDjI810B8tqxR7nPM34EaPYXcklvHgSdGdkDwuGDbeLO//MVEBmWSYEIxFgwCR8EkBHu/oaj5yAbaY4ty8hIZvEOxISG8KNu7H2UKlzxLGNUm4IMGKCDS9zddSAetUWE38cAkj/ifT90II0NdgFDJwSpFL3Vf03utiJsF1f7dUfULGOxWheBZlg1S39BIz4IIkCLnfr74bUibT2z8Yl1HU4PVJyWxR/zE7IsDaNkQNRlyGNug86EpfOFN8edk+TCw1DEAEhNklt0H61XOp/+V0we2Jcd7D+ZWyNjDWWU1SxdNWClUdsoSkeq0IOE5tuHFonC2J2UEcWSaczB8hgLBidDpIBTIJqa62S2y5Ih1zACno5dBqXQuvN16aS4lLarwK+wE9sRHuVkhLCMxVNaCVA84rnBgthyfU8SU9oDXw5u3i1zJUNBD5BzMZtvRE98bIQU59ntHzOQSSNMvhGSmYxYpRNi1AExRzzq2VD42CvQJJqW/euRZdHtkDWxKuD3hDxnzbMr6YHdnw8ZVjfat5kQvYyTG75tSN5Phofgl0Ykqj8oOLpXhJRhMdAVLF6+iSmN89ZN9tp/JCCogqS5+71TUToFjuoJ1QMaZshomEURpo9ggp1j9r+L5kcnjQDQrKUXpAxYXtQTbRTJz6c=
  run: npm start
