language: node_js
node_js:
  - 6
before_install:
  - npm i -g npm@3.10.10
install:
  - npm install jui
  - npm install jui-core
  - npm install jui-grid
  - npm install jui-chart
  - npm install chai
  - npm install mocha
  - npm install express
  - npm install body-parser
  - npm install cookie-parser
  - npm install multer
  - npm install stylus
  - npm install nib
