language: node_js
node_js:
- 6
before_install:
- npm i -g npm@3.10.10
install:
- npm install jui
- npm install jui-core
- npm install jui-grid
- npm install jui-chart
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
deploy:
  provider: heroku
  api_key:
    secure: vgXtgmDVqS65b/Pfxgfh1F1Q3IMNqHWgkdYbCWUI8lyOmSpPlNgGuEKEYG5yAdbInJTx+mNvLS4YQz5qv6qyJEl5z8e6TmAslhYvO00D73KKXgHeghj7jtpiK/VH4HLFBYqtSMo1M6/KJl85yZkAqP58EqtGfGSOEwEgrPgCKNskvhSgHkTrszx0xJQZbkfEo1HfyMrpb0cz1jfRY1DWZ57y5JwG4hLgyep5Fc3o+7aGUFNjSoMNmru0QQu6TkPeikIK0RcQNZWcDso5SEqAPIfizFaZpC7GoW9gCYmauekL/XafNsdxwm1r0spw1cE9+jFeNkM9NrR0HQs54LAzsmUuQYZuWDtNtLo1PoeWfKtbCyAdXVqGPnVoigYsV2IjaKSx8054PNQc8e+hxKziy5uMRi58bX5mltNCiBsEtee0fnviCPuBlfhDCYa+QRNFltvpRQOKIShDUSw8qXnj9oxeqQ0gc/+RFyQe4IfcdBDKmDPCh+iay4pSRy4bpVqlg4KcIRkXH1XV+owaMcrt80sN1l9j4ctJ0UPvyvUtAoasg1LA9d1xCVeyVVvLKufGB8Ktn6wqifs74sSbP1djfCc2agv3I0721wdsJO3v7qcSqBsOH/Bp3YUIXs2ULZV4pWI3ChqQM29DTntkt55uuTwCQ1atmfeMKmVCZ8AcOcU=
  run: npm start
